
/* eslint-disable */
/**
 * Generated API models.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * 
 * This is a mocked version to unblock the UI.
 */
import { anyApi } from "convex/server";

const api: any = anyApi;

// Explicitly define the structure to help the IDE and hooks
api.messages = {
    listConversations: "messages:listConversations",
    getMessages: "messages:getMessages",
    sendMessage: "messages:sendMessage",
    createConversation: "messages:createConversation",
};

api.tasks = {
    listHabits: "tasks:listHabits",
    addHabit: "tasks:addHabit",
    toggleHabit: "tasks:toggleHabit",
    deleteHabit: "tasks:deleteHabit",
};

api.users = {
    getStats: "users:getStats",
    updateScore: "users:updateScore",
    getPreferences: "users:getPreferences",
    updateAvatar: "users:updateAvatar",
};

export { api };
