
/* eslint-disable */
/**
 * Generated utility functions for implementing Convex functions.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 */
import {
    mutationGeneric,
    queryGeneric,
    actionGeneric,
    httpActionGeneric,
} from "convex/server";
import type { DataModel } from "./dataModel.d.ts";

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const action = actionGeneric;
export const httpAction = httpActionGeneric;
